<?php

namespace App\Other\Constraint\Group;

class InitialGroup extends AbstractGroup
{
    public function __construct(
        string $string,
        string $delimiter = ','
    )
    {
        parent::__construct($string, $delimiter);
    }

    public function hidden(): bool
    {
        return $this->contains('hidden');
    }

    public function public(): bool
    {
        return !$this->hidden();
    }

    /**
     * @param string $then
     * @return DefinitionGroup[]
     */
    public function split(string $then): array
    {
        return parent::split($then); // TODO: Change the autogenerated stub
    }
}